// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shkomwlzumwtdroagczc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoa29td2x6dW13dGRyb2FnY3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTY2MDgsImV4cCI6MjA3MzMzMjYwOH0.cLXiubte_aYQr4UAT4Ud_PULMdRwg2OiinqX5YFdCb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});